"""empty message

Revision ID: 004766e0c634
Revises: 9f31208dc33e
Create Date: 2024-03-26 14:07:52.255050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "004766e0c634"
down_revision: Union[str, None] = "9f31208dc33e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_transactions_recipient_address"),
        "transactions",
        ["recipient_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_sender_address"),
        "transactions",
        ["sender_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_sender_address"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_recipient_address"), table_name="transactions")
    # ### end Alembic commands ###
