"""empty message

Revision ID: 45c5d86a2a29
Revises: 73a8cbf157c3
Create Date: 2024-03-18 20:47:38.762442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c5d86a2a29'
down_revision: Union[str, None] = '73a8cbf157c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('block_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block', 'block_hash')
    # ### end Alembic commands ###
