"""empty message

Revision ID: 73a8cbf157c3
Revises: db6e4a9b01ea
Create Date: 2024-03-18 15:26:31.098291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73a8cbf157c3"
down_revision: Union[str, None] = "db6e4a9b01ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("amount", sa.Integer(), nullable=False))
    op.drop_column("transactions", "value")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("value", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("transactions", "amount")
    # ### end Alembic commands ###
