"""empty message

Revision ID: 81396b4c6d04
Revises: ee3fd4166e49
Create Date: 2024-04-23 21:07:56.789869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81396b4c6d04'
down_revision: Union[str, None] = 'ee3fd4166e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('block_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'block_number')
    # ### end Alembic commands ###
