"""empty message

Revision ID: 9f31208dc33e
Revises: 8da8420576da
Create Date: 2024-03-26 14:01:37.751028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f31208dc33e"
down_revision: Union[str, None] = "8da8420576da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.NUMERIC(precision=2, scale=2),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.BIGINT(),
        type_=sa.NUMERIC(precision=2, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
