"""empty message

Revision ID: cf287d115065
Revises: 45c5d86a2a29
Create Date: 2024-03-18 20:52:14.701708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf287d115065'
down_revision: Union[str, None] = '45c5d86a2a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'block', ['block_hash'])
    op.create_unique_constraint(None, 'block', ['merkle_root'])
    op.create_unique_constraint(None, 'block', ['nonce'])
    op.create_unique_constraint(None, 'block', ['previous_hash'])
    op.create_unique_constraint(None, 'transactions', ['transaction_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'block', type_='unique')
    op.drop_constraint(None, 'block', type_='unique')
    op.drop_constraint(None, 'block', type_='unique')
    op.drop_constraint(None, 'block', type_='unique')
    # ### end Alembic commands ###
