"""empty message

Revision ID: dd7cc63002ed
Revises: 004766e0c634
Create Date: 2024-04-02 14:09:21.012825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd7cc63002ed"
down_revision: Union[str, None] = "004766e0c634"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("block", sa.Column("authority_id", sa.String(), nullable=False))
    op.drop_constraint("block_nonce_key", "block", type_="unique")
    op.drop_column("block", "nonce")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "block", sa.Column("nonce", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("block_nonce_key", "block", ["nonce"])
    op.drop_column("block", "authority_id")
    # ### end Alembic commands ###
