"""empty message

Revision ID: ee3fd4166e49
Revises: dd7cc63002ed
Create Date: 2024-04-10 23:40:17.977040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee3fd4166e49"
down_revision: Union[str, None] = "dd7cc63002ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("block", "merkle_root", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("block", "merkle_root", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
