"""empty message

Revision ID: efc133a3c757
Revises: 7477f995b497
Create Date: 2024-03-26 13:49:49.929138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efc133a3c757"
down_revision: Union[str, None] = "7477f995b497"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.NUMERIC(precision=2, scale=0),
        type_=sa.Numeric(precision=2, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.Numeric(precision=2, scale=2),
        type_=sa.NUMERIC(precision=2, scale=0),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
