GENESIS_BLOCK_PREVIOUS_HASH = "genesis"
NO_BLOCK_PREVIOUS_HASH = "NONE"

PUBLIC_KEY_LENGTH = 32
AMOUNT_LENGTH = 8
TIMESTAMP_LENGTH = 4
RANDOM_DATA_LENGTH = 4
SIGN_LENGTH = 64
TRANSACTION_PURE_LENGTH = 81
MIN_BLOCK_RELEASE_TIME = 10 * 1000000
